<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting" Version="13.5.2" />
    <PackageVersion Include="Aspire.Hosting.Docker" Version="13.5.2" />
    <PackageVersion Include="Aspire.Hosting.RabbitMQ" Version="13.5.2" />
    <PackageVersion Include="Aspire.Hosting.Testing" Version="13.5.2" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.301" />
    <PackageVersion Include="RabbitMQ.Client" Version="7.2.2" />
    <PackageVersion Include="TigerBeetle" Version="0.17.9" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>
